title: Marco Bravo
author: Marco Bravo
description: If you don’t know, ask – if you know, share! ~ opensource mindset ⚾ {% include footer.html %}
theme: jekyll-theme-minimal
encoding: UTF-8
logo: images/cloud-pinata.jpeg
show_downloads: false
google_analytics:
