title: Marco Bravo
author: Marco Bravo
description: >
  <a href="https://dev.to/marcobravoram">
    <img src="https://d2fltix0v2e0sb.cloudfront.net/dev-badge.svg" alt="Marco Bravo's DEV Profile" height="30" width="30">
  </a>
  If you don’t know, ask – if you know, share! ~ opensource mindset 
  <img alt="Baseball ball image" src="https://github.githubassets.com/images/icons/emoji/unicode/26be.png" width="15" height="15" />
  <hr>
  “Lack of direction, not lack of time, is the problem.” ~ Zig Ziglar
  <hr>
  What do I want to do next? 	➠
  “Just take the next small step” ~ Paulo Coelho <br />	➠
  "Do what you can, with what you have, where you are." - Teddy Roosevelt
  <center>
    <img alt="Cloud and rainbow image" align="top" src="https://pbs.twimg.com/media/EU81RrLXkAATDjL?format=jpg&name=240x240">
  </center>
theme: jekyll-theme-minimal
encoding: UTF-8
logo: images/cloud-pinata.jpeg
show_downloads: false
google_analytics:
