title: Marco Bravo
author: Marco Bravo
description: If you don’t know, ask – if you know, share! ~ opensource mindset ⚾
theme: jekyll-theme-minimal
encoding: UTF-8
logo: images/cloud-pinata.jpeg
show_downloads: false
google_analytics:
#permalink: /blog/:year/:month/:day/:title
paginate: 5
