title: Marco Bravo
author: Marco Bravo
description: >
  <a href="https://dev.to/marcobravoram">
    <img src="https://d2fltix0v2e0sb.cloudfront.net/dev-badge.svg" alt="Marco Bravo's DEV Profile" height="30" width="30">
  </a>
  If you don’t know, ask – if you know, share! ~ opensource mindset 
  <img alt="Baseball ball image" src="https://github.githubassets.com/images/icons/emoji/unicode/26be.png" width="15" height="15" />
  <hr>
  ➠ "We may not have control over our circumstances, but we do have control over our minds" <br />
  ➠ “Lack of direction, not lack of time, is the problem.” ~ Zig Ziglar <br />
  ➠ What do I want to do next? <br />
  ➠ “Take the next small step” ~ Coelho <br />
  ➠ "While we teach, we learn" ~ Seneca <br />
  ➠ "The difficult we do immediately; the impossible takes a little longer" <br />
  ➠ "There is but one solution to the intricate riddle of life; to improve ourselves, and contribute to the happiness of others." --Mary Shelley, The Last Man. <br />
  ➠ “Your beliefs become your thoughts,
Your thoughts become your words,
Your words become your actions,
Your actions become your habits,
Your habits become your values,
Your values become your destiny.” ~ Gandhi
  <center>
    <img alt="Cloud and rainbow image" align="top" src="https://pbs.twimg.com/media/EU81RrLXkAATDjL?format=jpg&name=240x240">
  </center>
theme: jekyll-theme-minimal
encoding: UTF-8
logo: images/cloud-pinata.jpeg
show_downloads: false
google_analytics:
