title: Marco Bravo
author: Marco Bravo
description: >
  If you don’t know, ask – if you know, share! ~ opensource mindset 
  <img alt="Baseball ball image" src="https://github.githubassets.com/images/icons/emoji/unicode/26be.png" width="15" height="15" />
  <hr>
  “Lack of direction, not lack of time, is the problem. We all have twenty-four hour days.” ~ Zig Ziglar
  <hr>
  “When in doubt, just take the next small step” ~ Paulo Coelho
theme: jekyll-theme-minimal
encoding: UTF-8
logo: images/cloud-pinata.jpeg
show_downloads: false
google_analytics:
